language: node_js
sudo: false
env:
- CXX=g++-4.8
node_js:
- '6'
before_install:
- '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16'
before_script:
- psql -c 'create database travis;' -U postgres
- psql -c 'create schema salesforce;' -U postgres travis
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
cache:
  directories:
  - node_modules
services:

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
